version: '3.8'

services:
  api:
    build: ./api
    image: ghcr.io/daddyholnes/podplay-build-dev-api:latest
    container_name: podplay-build-api
    restart: always
    ports:
      - ${API_PORT:-3080}:${API_PORT:-3080}
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=${NODE_ENV:-production}
      - MONGO_URI=mongodb://mongodb:27017/podplay-build
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
      - API_PORT=${API_PORT:-3080}
    env_file:
      - .env
    depends_on:
      - mongodb
      - meilisearch

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.5.1
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-}
    volumes:
      - ./meili_data:/meili_data

  client:
    image: nginx:1.27.0-alpine
    container_name: podplay-build-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  pgdata2:
