version: '3.8'

services:
  api:
    # Changed from LibreChat to Podplay-Build
    container_name: podplay-build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_COMMIT: ${APP_COMMIT:-local-build}
    # Image name will need updating in GitHub repo as well
    image: ghcr.io/daddyholnes/podplay-build-dev:latest
    ports:
      - 3080:3080
    restart: always
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/podplay-build
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-}
      # See the Meilisearch section in the docs for more info and optimization
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENABLE_INIT_SYNC_INDEX=true
    env_file:
      - .env
    depends_on:
      - mongodb
      - meilisearch
    volumes:
      - /app/client/dist
      - /app/node_modules
      - ./api:/app/api
      - ./client:/app/client
      - ./packages:/app/packages
      - ./server:/app/server
      - ./transitions:/app/transitions
      - ./tools:/app/tools
      - ./config:/app/config
      - ./.env.example:/app/.env.example
      - ./uploads:/app/uploads
      - ./vite.config.js:/app/vite.config.js
      - ./test:/app/test
      - ./jest.config.js:/app/jest.config.js
      - ./babel.config.js:/app/babel.config.js

  rag-api-lite:
    # Changed from librechat-rag-api to podplay-build-rag-api
    image: ghcr.io/daddyholnes/podplay-build-rag-api-dev-lite:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: ${RAG_CONTAINER_MEMORY:-1G}
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - 3045:3045
    volumes:
      - ./rag.yml:/app/rag.yml
      - ./uploads:/app/uploads
      - ./vectorCache:/app/vectorCache

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongodb-data:/data/db

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.5.1
    restart: always
    ports:
      - 7700:7700
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
